blog/config/routes.rb
Rails.application.routes.draw do
  root 'topics#index'
  resources :topics
  get 'song_mixer/clean'

  get 'song_mixer/raw'

end

blog/app/models/song.rb
class Song < ActiveRecord::Base

    def initialize(name, artist, genre)
        @name = name
        @artist = artist
        @genre = genre
    end
    attr_accessor :name
        
end

blog/app/models/topic.rb
class Topic < ActiveRecord::Base
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/song_mixer_controller.rb
class SongMixerController < ApplicationController
  before_action :set_songs, only: [:clean, :raw]
  def initialize (clean, raw)
    @clean = clean
    @raw = raw
  end
  #Get the clean View
  def clean
    @songs = Songs.clean
  end

  def raw
  end
end

blog/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  attr_reader :topic
  
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    topic = Topic.find(params[:id])
    render json: post 
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.js 
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.js {render :layout => false }
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
      format.js {render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description)
    end
end

blog/app/helpers/song_mixer_helper.rb
module SongMixerHelper
end

blog/app/helpers/topics_helper.rb
module TopicsHelper
end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

blog/app/views/song_mixer/clean.html.erb
<h1>SongMixer#clean</h1>
<p>Find me in app/views/song_mixer/clean.html.erb</p>

blog/app/views/song_mixer/raw.html.erb
<h1>SongMixer#raw</h1>
<p>Find me in app/views/song_mixer/raw.html.erb</p>

blog/app/views/topics/_form.html.erb
<%= form_for @topic, :remote => true do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/topics/_topic.html.erb
<%= stylesheet_link_tag "index" %>
<tr id='row<%=topic.id %>'>
        <td class= 'content'><%= topic.title %></td>
        <td class= 'content'><%= topic.description %></td>
        <td ><%= link_to 'Show', topic, :remote => true %></td>
        <td ><%= link_to 'Edit', edit_topic_path(topic), :remote =>true %></td>
        <td ><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } , :remote => true , :class => 'delete_topic'  %></td>
</tr>
                          

blog/app/views/topics/create.js.erb
$('#new-topic form').remove();
$('#new-topic a').show();
$('table#topic tbody').append("<%= j render @topic %>");

blog/app/views/topics/destroy.js.erb
$('.delete_topic').bind('ajax:success', function() {
   $(this).closest('tr').hide();
});

blog/app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

blog/app/views/topics/edit.js.erb
$('#edit-topic').append("<%= j render 'form', topic: @topic %>")

blog/app/views/topics/index.html.erb
<%= stylesheet_link_tag "index" %>
<p id="notice"><%= notice %></p>

<h1>Listing Topics</h1>

<table id='topic'>
  <thead>
    <tr>
      <th width= '40%'>Title</th>
      <th width= '40%'>Description</th>
      <th width= '20%' colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'topic', collection: @topics %>
  </tbody>
</table>

<br>

<div id='new-topic'>
  <%= link_to 'New Topic', new_topic_path, :remote =>true, :class =>'new_topic' %>
</div>

<div id='edit-topic'>

</div>

blog/app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

blog/app/views/topics/new.js.erb
$('#new-topic a').hide().parent().append("<%= j render 'form', topic: @topic %>")

blog/app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>

blog/app/views/topics/update.js.erb
$('#edit-topic form').remove()

$('#edit-topic').append('Row Id is ' +$('#row') +'<%=@topic.id %>')
id ='<%=@topic.id %>'

$('table'+'#topic'+' tbody '+'tr#row'+id).html('<%= j render @topic%>') 